services:
    # Video Manager Pro API credentials instance
    vmpro_api.credentials:
        class: MovingImage\Client\VMPro\Entity\ApiCredentials
        arguments:
            - "%vm_pro_api_credentials_username%"
            - "%vm_pro_api_credentials_password%"

    # JWT Token extractor instance
    vmpro_api.token_extractor:
        class: MovingImage\Client\VMPro\Extractor\TokenExtractor

    # Dedicated JMS Serializer instance
    vmpro_api.serializer:
        class: JMS\Serializer
        factory: ["@vmpro_api.api_client_factory", createSerializer]

    # Token manager instance used for managing the authentication
    # access + refresh token state
    vmpro_api.token_manager:
        class: MovingImage\Client\VMPro\Manager\TokenManager
        arguments:
            - "@vmpro_api.unauthenticated_guzzle_client"
            - "@vmpro_api.credentials"
            - "@vmpro_api.token_extractor"

    # Event listener that will bypass cache for requests that have the pre-defined request argument
    # The name of this request argument is configured using `cache_bypass_argument` option
    vmpro_api.bypass_cache_listener:
        class: MovingImage\Bundle\VMProApiBundle\EventListener\BypassCacheListener
        arguments:
            - '@service_container'
            - '%vm_pro_api_cache_bypass_argument%'
        tags:
            - { name: kernel.event_subscriber }