services:
    # Video Manager Pro API credentials instance
    vmpro_api.credentials:
        class: MovingImage\Client\VMPro\Entity\ApiCredentials
        arguments:
            - "%vm_pro_api_credentials_username%"
            - "%vm_pro_api_credentials_password%"

    # JWT Token extractor instance
    vmpro_api.token_extractor:
        class: MovingImage\Client\VMPro\Extractor\TokenExtractor

    # Dedicated JMS Serializer instance
    vmpro_api.serializer:
        class: JMS\Serializer
        factory: ["@vmpro_api.api_client_factory", createSerializer]

    # Token manager instance used for managing the authentication
    # access + refresh token state
    vmpro_api.token_manager:
        class: MovingImage\Client\VMPro\Manager\TokenManager
        arguments:
            - "@vmpro_api.unauthenticated_guzzle_client"
            - "@vmpro_api.credentials"
            - "@vmpro_api.token_extractor"

    # Video Manager Pro API client - dynamically instantiated
    # depending on which GuzzleHttp library is present in the project
    vmpro_api.client:
        class: MovingImage\Client\VMPro\Interfaces\ApiClientInterface
        factory: ["@vmpro_api.api_client_factory", create]
        arguments:
            - "@vmpro_api.authenticated_guzzle_client"
            - "@vmpro_api.serializer"